
import { Product, User, Order, Bounty, Complaint, Team, Announcement, AdSlot, OrderStatus, BountyStatus, ComplaintStatus, HitterIdentity, HitterIdentitySetting, HitterLevelSetting } from './types';

export const allUsers: User[] = [
    { 
        id: '1', 
        name: '玩家_8888', 
        email: 'user1@example.com', 
        role: 'User', 
        status: 'Active',
        balance: 807.14,
        deposit: 500.00,
        frozenBalance: 0.00,
        unfreezableBalance: 0,
        freezingBalance: 0,
        toBePaid: 0,
        paidOut: 156.6,
        hitterLevel: '新手打手',
        hitterIdentity: HitterIdentity.Normal,
        vipLevel: 'VIP 1',
        incomeLevel: '收入等级1',
        seniorityLevel: '资历等级1',
        badges: ['平台新星'],
        teamId: 'T2',
        uplineUserId: 'U0',
    },
    { 
        id: '2', 
        name: '大神_001', 
        email: 'hitter1@example.com', 
        role: 'User', 
        status: 'Active',
        balance: 1500,
        deposit: 80, // Note: For VIP test, this is < 100
        frozenBalance: 200,
        unfreezableBalance: 50,
        freezingBalance: 150,
        toBePaid: 50,
        paidOut: 12000,
        hitterLevel: '大师打手',
        hitterIdentity: HitterIdentity.VIP,
        vipLevel: 'VIP 2',
        incomeLevel: '收入等级3',
        seniorityLevel: '资历等级2',
        badges: ['周冠军'],
        uplineUserId: 'U1',
        teamId: 'T1'
    },
    { 
        id: '3', 
        name: '土豪哥', 
        email: 'boss1@example.com', 
        role: 'User', 
        status: 'Frozen',
        balance: 10000,
        deposit: 1000,
        frozenBalance: 500,
        unfreezableBalance: 200,
        freezingBalance: 300,
        toBePaid: 200,
        paidOut: 25000,
        hitterLevel: '资深老板',
        hitterIdentity: HitterIdentity.None,
        vipLevel: 'VIP 5',
        incomeLevel: '收入等级5',
        seniorityLevel: '资历等级4',
        badges: ['富甲一方', '常胜将军'],
        teamId: 'T3',
        uplineUserId: 'U0',
    },
    { 
        id: '4', 
        name: '管理员A', 
        email: 'admin@example.com', 
        role: 'Admin', 
        status: 'Active',
        balance: 0,
        deposit: 0,
        frozenBalance: 0,
        unfreezableBalance: 0,
        freezingBalance: 0,
        toBePaid: 0,
        paidOut: 0,
        hitterLevel: 'N/A',
        hitterIdentity: HitterIdentity.Auditor,
        vipLevel: 'N/A',
        incomeLevel: 'N/A',
        seniorityLevel: 'N/A',
        badges: ['管理员'],
    },
    // New Hitters for leaderboard
    {
        id: '5',
        name: '闪电侠',
        email: 'hitter2@example.com',
        role: 'User',
        status: 'Active',
        balance: 850,
        deposit: 200,
        frozenBalance: 50,
        unfreezableBalance: 0,
        freezingBalance: 50,
        toBePaid: 0,
        paidOut: 28500,
        hitterLevel: '荣耀王者',
        hitterIdentity: HitterIdentity.SuperVIP,
        vipLevel: 'VIP 4',
        incomeLevel: '收入等级4',
        seniorityLevel: '资历等级3',
        badges: ['月冠军', '效率之星'],
        teamId: 'T1',
        uplineUserId: 'U2',
    },
    {
        id: '6',
        name: '狙神',
        email: 'hitter3@example.com',
        role: 'User',
        status: 'Active',
        balance: 2100,
        deposit: 150,
        frozenBalance: 100,
        unfreezableBalance: 100,
        freezingBalance: 0,
        toBePaid: 100,
        paidOut: 19800,
        hitterLevel: '大师打手',
        hitterIdentity: HitterIdentity.VIP,
        vipLevel: 'VIP 3',
        incomeLevel: '收入等级3',
        seniorityLevel: '资历等级3',
        badges: ['神射手'],
        uplineUserId: 'U2',
    },
    {
        id: '7',
        name: '法王',
        email: 'hitter4@example.com',
        role: 'User',
        status: 'Active',
        balance: 500,
        deposit: 100,
        frozenBalance: 0,
        unfreezableBalance: 0,
        freezingBalance: 0,
        toBePaid: 0,
        paidOut: 15200,
        hitterLevel: '钻石打手',
        hitterIdentity: HitterIdentity.VIP,
        vipLevel: 'VIP 2',
        incomeLevel: '收入等级2',
        seniorityLevel: '资历等级2',
        badges: [],
        uplineUserId: 'U1',
    },
     {
        id: '8',
        name: '小透明',
        email: 'hitter5@example.com',
        role: 'User',
        status: 'Active',
        balance: 150,
        deposit: 50,
        frozenBalance: 0,
        unfreezableBalance: 0,
        freezingBalance: 0,
        toBePaid: 0,
        paidOut: 800,
        hitterLevel: '青铜打手',
        hitterIdentity: HitterIdentity.Normal,
        vipLevel: '无',
        incomeLevel: '收入等级1',
        seniorityLevel: '资历等级1',
        badges: ['平台新星'],
        uplineUserId: 'U7',
    },
];

export const allProducts: Product[] = [
  { id: '1', name: '大师级陪练', price: 50, images: ['https://picsum.photos/seed/cat1/800/600', 'https://picsum.photos/seed/cat1-2/800/600'], sales: 1200, category: '技能陪练', description: '由顶尖大师级玩家提供一对一陪练服务，快速提升您的游戏技巧和意识。', serviceFee: 10 },
  { id: '2', name: '极速上分套餐', price: 100, images: ['https://picsum.photos/seed/cat2/800/600'], sales: 950, category: '段位提升', description: '专业团队为您提供高效的上分服务，安全可靠，助您轻松达到理想段位。', serviceFee: 15 },
  { id: '3', name: '团队开黑语音', price: 20, images: ['https://picsum.photos/seed/cat3/800/600', 'https://picsum.photos/seed/cat3-2/800/600'], sales: 2500, category: '语音互动', description: '加入我们的语音频道，与队友实时沟通，享受团队游戏的乐趣。', serviceFee: 5 },
  { id: '4', name: '大神带队通关', price: 80, images: ['https://picsum.photos/seed/cat4/800/600'], sales: 700, category: '副本攻略', description: '资深玩家带队，轻松攻克高难度副本，获取稀有装备。', serviceFee: 12 },
  { id: '5', name: '娱乐休闲匹配', price: 15, images: ['https://picsum.photos/seed/cat5/800/600', 'https://picsum.photos/seed/cat5-2/800/600', 'https://picsum.photos/seed/cat5-3/800/600'], sales: 3000, category: '技能陪练', description: '轻松愉快的游戏体验，大神陪你聊天、玩游戏，告别孤单。', serviceFee: 5 },
  { id: '6', name: '王者晋级赛', price: 120, images: ['https://picsum.photos/seed/cat6/800/600'], sales: 500, category: '段位提升', description: '关键的晋级赛，我们保证100%成功率，让您稳操胜券。', serviceFee: 20 },
  { id: '7', name: '声优聊天互动', price: 30, images: ['https://picsum.photos/seed/cat7/800/600'], sales: 1500, category: '语音互动', description: '选择你喜欢的声音，陪你聊天，唱歌，玩游戏。', serviceFee: 8 },
  { id: '8', name: '全英雄教学', price: 60, images: ['https://picsum.photos/seed/cat8/800/600'], sales: 400, category: '技能陪练', description: '专业玩家手把手教你任意英雄的玩法和技巧。', serviceFee: 10 },
  { id: '9', name: '赛季末冲刺', price: 150, images: ['https://picsum.photos/seed/cat9/800/600'], sales: 300, category: '段位提升', badge: '限时优惠', description: '赛季末最后冲刺，价格优惠，效率保证。', serviceFee: 18 },
  { id: '10', name: '地狱模式开荒', price: 200, images: ['https://picsum.photos/seed/cat10/800/600'], sales: 150, category: '副本攻略', description: '挑战最难的地狱模式副本，专业指挥带队。', serviceFee: 25 },
  {
    id: 'vip_cert_01',
    name: 'VIP打手认证',
    price: 100,
    images: ['https://picsum.photos/seed/vipcert/800/600'],
    sales: 15,
    category: 'VIP打手认证',
    description: '购买后立即获得VIP打手资格，解锁更多接单特权和专属标识。保证金需满足100元要求。',
    specialType: 'vip_certification',
    grantsIdentity: HitterIdentity.VIP,
    serviceFee: 50,
  },
  { id: 'assess_01', name: '初级考核单', price: 20, images: ['https://picsum.photos/seed/assess1/800/600'], sales: 120, category: '打手考核', description: '适用于新手打手，考核通过后可接初级订单。', specialType: 'assessment', grantsIdentity: HitterIdentity.Normal, serviceFee: 30 },
  { id: 'assess_02', name: '中级考核单', price: 50, images: ['https://picsum.photos/seed/assess2/800/600'], sales: 85, category: '打手考核', description: '适用于有一定经验的打手，考核通过后解锁更高奖励的订单。', specialType: 'assessment' },
  { id: 'assess_03', name: '高级考核单', price: 80, images: ['https://picsum.photos/seed/assess3/800/600'], sales: 40, category: '打手考核', description: '面向顶尖玩家，通过后成为平台认证的大师级打手。', specialType: 'assessment' },
];

export const allOrders: Order[] = [
    { 
        id: '2025092719221964785178', 
        productName: '必须打25格红', 
        status: OrderStatus.PendingAccept, 
        amount: 666.00, 
        userId: '3', 
        userName: '土豪哥',
        platform: 'mobile',
        productId: '2',
        category: '段位提升',
        gameId: '接单后可查看',
        server: '手机端',
        notes: '指定猫咪',
        textId: '接单后可查看',
        orderTime: '2025-09-27 19:34:08',
        acceptTime: null,
        completionTime: null,
    },
    { 
        id: '2025092719221964785179', 
        productName: '绝密体验单 (保底520万)', 
        status: OrderStatus.PendingAccept, 
        amount: 88.88, 
        userId: '1', 
        userName: '玩家_8888',
        platform: 'pc',
        productId: '4',
        category: '副本攻略',
        gameId: 'AB-12345',
        server: '电脑端',
        notes: '打绝密局 保底520万！不卡保底.全网最低价格！',
        textId: 'TEXT-54321',
        orderTime: '2023-10-27 10:15:30',
        acceptTime: null,
        completionTime: null,
    },
    { 
        id: 'O3', 
        productName: '团队开黑语音', 
        status: OrderStatus.PendingSettlement, 
        amount: 20, 
        userId: '3', 
        userName: '土豪哥',
        hitterId: '2',
        productId: '3',
        category: '语音互动',
        gameId: 'N/A',
        server: '手机端',
        notes: '来个声音好听的',
        textId: 'VOICE-123',
        orderTime: '2023-10-28 11:00:00',
        acceptTime: '2023-10-28 11:05:12',
        completionTime: null,
    },
    { 
        id: 'O4', 
        productName: '大神带队通关', 
        status: OrderStatus.InProgress, 
        amount: 80, 
        userId: '1', 
        userName: '玩家_8888',
        hitterId: '2',
        platform: 'pc',
        productId: '4',
        category: '副本攻略',
        gameId: 'CD-54321',
        server: '电脑端',
        notes: '速通，来效率高的',
        textId: 'RAID-987',
        orderTime: '2023-10-29 14:20:05',
        acceptTime: '2023-10-29 14:25:10',
        completionTime: null,
    },
    { 
        id: '2025092719221964785180', 
        productName: '王者晋级赛', 
        status: OrderStatus.PendingAccept, 
        amount: 120, 
        userId: '3', 
        userName: '土豪哥',
        platform: 'mobile',
        productId: '6',
        category: '段位提升',
        gameId: '接单后可查看',
        server: '手机端',
        notes: '来个稳的，输一把全额退款',
        textId: '接单后可查看',
        orderTime: '2023-10-30 09:00:00',
        acceptTime: null,
        completionTime: null,
    },
    { 
        id: 'O1', 
        productName: '大师级陪练', 
        status: OrderStatus.Completed, 
        amount: 50, 
        userId: '1', 
        userName: '玩家_8888',
        hitterId: '6',
        platform: 'pc',
        productId: '1',
        category: '技能陪练',
        gameId: 'EF-99999',
        server: '电脑端',
        notes: '复盘讲解',
        textId: 'TUTOR-456',
        orderTime: '2023-10-26 18:00:00',
        acceptTime: '2023-10-26 18:10:00',
        completionTime: '2023-10-26 19:10:00',
    },
];

export const allBounties: Bounty[] = [
  { id: '1', title: '急求大神带过最终BOSS', description: '卡关一天了，来个强力输出，酬金丰厚！', reward: 200, status: BountyStatus.InProgress, participants: 2, maxParticipants: 3, platform: 'pc' },
  { id: '2', title: '五排车队缺一辅助', description: '来个会玩的辅助，心态好，不压力。', reward: 50, status: BountyStatus.InProgress, participants: 4, maxParticipants: 5, platform: 'mobile' },
  { id: '3', title: '新赛季开荒团', description: '招募长期队友一起开荒，要求时间稳定。', reward: 100, status: BountyStatus.Completed, participants: 5, maxParticipants: 5, platform: 'pc' },
];

export const allComplaints: Complaint[] = [
    { id: 'C1', orderId: 'O2', userId: '2', userName: '大神_001', subject: '服务时长不足', details: '陪练服务原定1小时，实际只有50分钟。', status: ComplaintStatus.Pending, createdAt: '2023-10-28' },
    { id: 'C2', orderId: 'O1', userId: '1', userName: '玩家_8888', subject: '账号登录异常', details: '完成服务后，我的账号无法正常登录，怀疑有安全风险。', status: ComplaintStatus.Resolved, createdAt: '2023-10-27' },
];

export const allTeams: Team[] = [
    { id: 'T1', name: '王者荣耀冲分队', leaderName: '大神_001', leaderId: '2', memberCount: 5, status: 'Active', createdAt: '2023-10-25' },
    { id: 'T2', name: '休闲娱乐开车群', leaderName: '玩家_8888', leaderId: '1', memberCount: 23, status: 'Active', createdAt: '2023-10-20' },
    { id: 'T3', name: 'PVE开荒团', leaderName: '土豪哥', leaderId: '3', memberCount: 10, status: 'Frozen', createdAt: '2023-09-15' },
];

export const allAnnouncements: Announcement[] = [
    { id: 'A1', content: '平台将于午夜进行系统维护，请提前安排好您的订单。', createdAt: '2023-10-28', isActive: true },
    { id: 'A2', content: '国庆节活动上线！充值即送好礼，详情请见活动页面。', createdAt: '2023-09-30', isActive: true },
    { id: 'A3', content: '严禁使用第三方插件，一经发现将永久封号处理。', createdAt: '2023-09-15', isActive: false },
];

export const allAdSlots: AdSlot[] = [
    { id: 'ad-slot-1', name: '广告位 1 (首页)', content: '这是一个推广活动', link: '#' },
    { id: 'ad-slot-2', name: '广告位 2 (分类页)', content: '分类页专属优惠', link: '#' },
    { id: 'ad-slot-3', name: '广告位 3 (个人中心)', content: '邀请好友得奖励', link: '#' },
    { id: 'ad-slot-4', name: '广告位 4 (个人中心)', content: '成为VIP打手', link: '#' },
];

// NEW Mock data for settings
export const mockIdentitySettings: HitterIdentitySetting[] = [
    { identity: HitterIdentity.Normal, name: '普通打手', requiredProductId: 'assess_01', iconUrl: 'https://example.com/normal.png' },
    { identity: HitterIdentity.VIP, name: 'VIP打手', requiredProductId: 'vip_cert_01', iconUrl: 'https://example.com/vip.png' },
    { identity: HitterIdentity.SuperVIP, name: '超级VIP打手', requiredProductId: undefined, iconUrl: 'https://example.com/supervip.png' },
    { identity: HitterIdentity.Auditor, name: '审核员', requiredProductId: undefined, iconUrl: 'https://example.com/auditor.png' },
];

export const mockHitterLevelSettings: HitterLevelSetting[] = [
    { name: '青铜打手', requiredIncome: 0, haloColor: '#CD7F32' },
    { name: '白银打手', requiredIncome: 1000, haloColor: '#C0C0C0' },
    { name: '黄金打手', requiredIncome: 5000, haloColor: '#FFD700' },
    { name: '钻石打手', requiredIncome: 10000, haloColor: '#B9F2FF' },
    { name: '大师打手', requiredIncome: 20000, haloColor: '#E0B0FF' },
    { name: '荣耀王者', requiredIncome: 50000, haloColor: '#FF4500' },
];

export const mockBossLevelSettings: HitterLevelSetting[] = [
    { name: '1级老板', requiredIncome: 0, haloColor: '' },
    { name: '2级老板', requiredIncome: 1000, haloColor: '' },
    { name: '3级老板', requiredIncome: 5000, haloColor: '' },
    { name: '钻石老板', requiredIncome: 10000, haloColor: '' },
    { name: '至尊老板', requiredIncome: 50000, haloColor: '' },
];
